apiVersion: v1
kind: ReplicationController
metadata:
  namespace: default
  name: micro-api
spec:
  replicas: 1
  selector:
    name: micro-api
  template:
    metadata:
      labels:
        name: micro-api
    spec:
      containers:
        - name: api
          command: [
            "/micro",
            "--registry=consul",
            "--registry_address=$(REGISTRY_SERVICE_HOST)",
            "--logtostderr",
            "--register_ttl=60",
            "--register_interval=30",
            "api"
          ]
          image: microhq/micro
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
            name: api-port
