apiVersion: v1
kind: ReplicationController
metadata:
  namespace: default
  name: micro-car
spec:
  replicas: 1
  selector:
    name: micro-car
  template:
    metadata:
      labels:
        name: micro-car
    spec:
      containers:
        - name: car
          command: [ "/micro", "--registry=consul", "--registry_address=$(REGISTRY_SERVICE_HOST)", "--logtostderr", "sidecar" ]
          image: microhq/micro
          imagePullPolicy: Always
          ports:
          - containerPort: 8081
            name: car-port
