apiVersion: v1
kind: ReplicationController
metadata:
  namespace: default
  name: micro-car
spec:
  replicas: 1
  selector:
    name: micro-car
  template:
    metadata:
      labels:
        name: micro-car
    spec:
      containers:
        - name: car
          resources:
            limits:
              cpu: "10m"
          command: [
            "/micro",
            "--registry=consul",
            "--registry_address=$(REGISTRY_SERVICE_HOST)",
            "--logtostderr",
            "--register_ttl=60",
            "--register_interval=30",
            "--enable_stats",
            "sidecar"
          ]
          image: microhq/micro
          imagePullPolicy: Always
          ports:
          - containerPort: 8081
            name: car-port
