apiVersion: v1
kind: ReplicationController
metadata:
  namespace: default
  name: micro-web
spec:
  replicas: 1
  selector:
    name: micro-web
  template:
    metadata:
      labels:
        name: micro-web
    spec:
      containers:
        - name: web
          resources:
            limits:
              cpu: "10m"
          command: [ "/micro", "--registry=consul", "--registry_address=$(REGISTRY_SERVICE_HOST)", "--logtostderr", "web" ]
          image: microhq/micro
          imagePullPolicy: Always
          ports:
          - containerPort: 8082
            name: web-port
