apiVersion: v1
kind: ReplicationController
metadata:
  namespace: default
  name: geo-web
spec:
  replicas: 1
  selector:
    name: geo-web
  template:
    metadata:
      labels:
        name: geo-web
    spec:
      containers:
        - name: geo-web
          resources:
            limits:
              cpu: "50m"
          command: [
		"/geo-web",
		"--registry=consul",
		"--registry_address=$(REGISTRY_SERVICE_HOST)",
		"--logtostderr"
	  ]
          image: microhq/geo-web
          imagePullPolicy: Always
          ports:
          - containerPort: 9090
            name: geo-web-port
