apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: default
  name: greeter-srv
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: greeter-srv
        micro: go.micro.srv.greeter
    spec:
      containers:
        - name: discovery
          resources:
            limits:
              cpu: "10m"
          command: [
		"/greeter-srv",
		"--registry=kubernetes",
		"--selector=cache",
		"--server_address=0.0.0.0:9090",
		"--broker_address=0.0.0.0:10001"
	  ]
          image: microhq/greeter-srv:kubernetes
          imagePullPolicy: Always
          ports:
          - containerPort: 9090
            name: greeter-port
