apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: default
  name: greeter-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: greeter-api
    spec:
      containers:
        - name: discovery
          resources:
            requests:
              cpu: "20m"
          command: [
		"/greeter-api",
		"--registry=kubernetes",
		"--selector=cache",
		"--server_address=0.0.0.0:9090",
		"--broker_address=0.0.0.0:10001"
	  ]
          image: microhq/greeter-api:kubernetes
          imagePullPolicy: Always
          ports:
          - containerPort: 9090
            name: api-port
