apiVersion: v1
kind: ReplicationController
metadata:
  namespace: default
  name: discovery-web
spec:
  replicas: 1
  selector:
    name: discovery-web
  template:
    metadata:
      labels:
        name: discovery-web
    spec:
      containers:
        - name: discovery
          resources:
            limits:
              cpu: "10m"
          command: [
		"/platform",
		"--registry=consul",
		"--registry_address=$(REGISTRY_SERVICE_HOST)",
		"--server_address=0.0.0.0:9090",
		"--register_ttl=60",
		"--register_interval=30",
		"discovery",
		"web"
	  ]
          image: microhq/platform
          imagePullPolicy: Always
          ports:
          - containerPort: 9090
            name: discovery-port
