apiVersion: v1
kind: ReplicationController
metadata:
  namespace: default
  name: trace-web
spec:
  replicas: 1
  selector:
    name: trace-web
  template:
    metadata:
      labels:
        name: trace-web
    spec:
      containers:
        - name: trace
          resources:
            limits:
              cpu: "10m"
          command: [
                "/platform",
                "--registry=consul",
                "--registry_address=$(REGISTRY_SERVICE_HOST)",
                "--server_address=0.0.0.0:9090",
                "--register_ttl=60",
                "--register_interval=30",
                "trace",
                "web"
          ]
          image: microhq/platform
          imagePullPolicy: Always
          ports:
          - containerPort: 9090
            name: trace-port
