apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: default
  name: geo-srv
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: geo-srv
    spec:
      containers:
        - name: geo
          resources:
            requests:
              cpu: "35m"
          command: [
		"/geo-srv",
		"--registry=kubernetes",
		"--selector=cache",
		"--server_address=0.0.0.0:9090",
		"--broker_address=0.0.0.0:10001"
	  ]
          image: microhq/geo-srv:kubernetes
          imagePullPolicy: Always
          ports:
          - containerPort: 9090
            name: geo-srv-port
