apiVersion: v1
kind: ReplicationController
metadata:
  namespace: default
  name: platform-trace
spec:
  replicas: 1
  selector:
    name: platform-trace
  template:
    metadata:
      labels:
        name: platform-trace
    spec:
      containers:
        - name: trace
          command: [
		"/platform",
		"--registry=consul",
		"--registry_address=$(REGISTRY_SERVICE_HOST)",
		"--server_address=0.0.0.0:9090",
		"--broker_address=0.0.0.0:10001",
		"--database_url=trace:trace@tcp($(PXC_CLUSTER_SERVICE_HOST):$(PXC_CLUSTER_SERVICE_PORT))/trace",
		"--register_ttl=60",
		"--register_interval=30",
		"trace",
		"srv"
	  ]
          image: microhq/platform
          imagePullPolicy: Always
          ports:
          - containerPort: 9090
            name: trace-port
          - containerPort: 10001
            name: broker-port
