apiVersion: v1
kind: ReplicationController
metadata:
  namespace: default
  name: message-web
spec:
  replicas: 1
  selector:
    name: message-web
  template:
    metadata:
      labels:
        name: message-web
    spec:
      containers:
        - name: message-web
          resources:
            limits:
              cpu: "50m"
          command: [
		"/message-web",
		"--registry=consul",
		"--registry_address=$(REGISTRY_SERVICE_HOST)"
	  ]
          image: microhq/message-web
          imagePullPolicy: Always
          ports:
          - containerPort: 9090
            name: message-port
