apiVersion: v1
kind: ReplicationController
metadata:
  namespace: default
  name: greeter-srv
spec:
  replicas: 1
  selector:
    name: greeter-srv
  template:
    metadata:
      labels:
        name: greeter-srv
    spec:
      containers:
        - name: discovery
          resources:
            limits:
              cpu: "10m"
          command: [
		"/greeter-srv",
		"--registry=consul",
		"--registry_address=$(REGISTRY_SERVICE_HOST)",
		"--server_address=0.0.0.0:9090",
		"--broker_address=0.0.0.0:10001"
	  ]
          image: microhq/greeter-srv
          imagePullPolicy: Always
          ports:
          - containerPort: 9090
            name: greeter-port
